#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
# Klaude Monitor installer (per user, no root needed).
#
#   ./install.sh runtime [--hooks]   shared service: daemon, D-Bus/systemd files, CLI, hook, icon
#   ./install.sh panel               panel widget        (needs the runtime)
#   ./install.sh desktop             desktop widget      (needs the runtime)
#   ./install.sh all [--hooks]       runtime + both widgets
#   ./install.sh hooks               add the Claude Code hooks (all known config dirs)
#   ./install.sh uninstall-panel     remove the panel widget only
#   ./install.sh uninstall-desktop   remove the desktop widget only
#   ./install.sh uninstall-runtime [--purge]
#                                    stop and remove the service and the hooks
#                                    (--purge also deletes history and settings)
#   ./install.sh status
#
# Removing a widget never stops the service: the other widget keeps working.
set -eu

ROOT=$(cd "$(dirname "$0")" && pwd)
PREFIX=${PREFIX:-$HOME/.local}
BINDIR="$PREFIX/bin"
LIBDIR="$PREFIX/lib/klaude-monitor"
DATADIR=${XDG_DATA_HOME:-$HOME/.local/share}
CONFIGDIR=${XDG_CONFIG_HOME:-$HOME/.config}
STATEDIR=${XDG_STATE_HOME:-$HOME/.local/state}
UNITDIR="$CONFIGDIR/systemd/user"
BUS=io.github.aqu1ntero.KlaudeMonitor
PANEL_ID=io.github.aqu1ntero.klaudemonitor.panel
DESKTOP_ID=io.github.aqu1ntero.klaudemonitor.desktop

if [ -t 1 ]; then
  say() { printf '\033[1m==>\033[0m %s\n' "$*"; }
  warn() { printf '\033[33m!!\033[0m %s\n' "$*" >&2; }
else  # plain output when run from a widget
  say() { printf '==> %s\n' "$*"; }
  warn() { printf '!! %s\n' "$*" >&2; }
fi

python_bin() {
  # The daemon needs PyGObject (gi): prefer the system python, which ships it.
  for p in /usr/bin/python3 python3; do
    if command -v "$p" >/dev/null 2>&1 && "$p" -c 'import gi; gi.require_version("Gio", "2.0")' 2>/dev/null; then
      command -v "$p"
      return
    fi
  done
  return 1
}

install_runtime() {
  py=$(python_bin) || { warn "python3 with PyGObject (gi) is required (Debian/Ubuntu: python3-gi, Arch: python-gobject, Fedora: python3-gobject)"; exit 1; }
  say "Installing the shared service into $PREFIX"
  mkdir -p "$BINDIR" "$LIBDIR" "$UNITDIR" "$DATADIR/dbus-1/services" "$DATADIR/icons/hicolor/scalable/apps" "$DATADIR/applications"
  rm -rf "$LIBDIR/klaude_monitord"
  cp -r "$ROOT/daemon/klaude_monitord" "$LIBDIR/"
  find "$LIBDIR" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true

  cat >"$BINDIR/klaude-monitord" <<EOF
#!/bin/sh
# Klaude Monitor daemon launcher (generated by install.sh)
PYTHONPATH="$LIBDIR\${PYTHONPATH:+:\$PYTHONPATH}" exec "$py" -m klaude_monitord daemon "\$@"
EOF
  cat >"$BINDIR/klaude-monitor" <<EOF
#!/bin/sh
# Klaude Monitor CLI launcher (generated by install.sh)
PYTHONPATH="$LIBDIR\${PYTHONPATH:+:\$PYTHONPATH}" exec "$py" -m klaude_monitord "\$@"
EOF
  install -m 755 "$ROOT/hook/klaude-monitor-hook" "$BINDIR/klaude-monitor-hook"
  chmod 755 "$BINDIR/klaude-monitord" "$BINDIR/klaude-monitor"

  sed "s|@BINDIR@|$BINDIR|g" "$ROOT/data/klaude-monitord.service.in" >"$UNITDIR/klaude-monitord.service"
  sed "s|@BINDIR@|$BINDIR|g" "$ROOT/data/$BUS.service.in" >"$DATADIR/dbus-1/services/$BUS.service"
  cp "$ROOT/data/klaude-monitor.svg" "$DATADIR/icons/hicolor/scalable/apps/klaude-monitor.svg"
  cp "$ROOT/data/klaude-monitor.desktop" "$DATADIR/applications/klaude-monitor.desktop"
  command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -q "$DATADIR/icons/hicolor" 2>/dev/null || true

  if command -v systemctl >/dev/null 2>&1 && systemctl --user show-environment >/dev/null 2>&1; then
    systemctl --user daemon-reload
    systemctl --user enable klaude-monitord.service >/dev/null 2>&1 || true
    systemctl --user restart klaude-monitord.service
    say "Service enabled and (re)started: systemctl --user status klaude-monitord"
  else
    warn "systemd user session not available: the service will be started on demand through D-Bus"
  fi
  case ":$PATH:" in *":$BINDIR:"*) ;; *) warn "$BINDIR is not in PATH; the CLI is $BINDIR/klaude-monitor" ;; esac
}

install_hooks() {
  say "Adding the Claude Code hooks (a backup of each settings.json is kept as settings.json.klaude-monitor.bak)"
  "$BINDIR/klaude-monitor" hooks install --command "$BINDIR/klaude-monitor-hook"
}

need_kpackagetool() {
  command -v kpackagetool6 >/dev/null 2>&1 || { warn "kpackagetool6 not found (Plasma 6 is required for the widgets)"; exit 1; }
}

install_widget() {
  need_kpackagetool
  id=$1
  [ -d "$ROOT/build/$id" ] || sh "$ROOT/tools/build.sh" >/dev/null
  if kpackagetool6 -t Plasma/Applet -s "$id" >/dev/null 2>&1; then
    kpackagetool6 -t Plasma/Applet -u "$ROOT/build/$id" >/dev/null
    say "Upgraded widget $id (restart Plasma or re-add the widget to load the new version: systemctl --user restart plasma-plasmashell)"
  else
    kpackagetool6 -t Plasma/Applet -i "$ROOT/build/$id" >/dev/null
    say "Installed widget $id — add it from 'Add Widgets…' (search 'Klaude')"
  fi
  [ -x "$BINDIR/klaude-monitord" ] || warn "the shared service is not installed yet: run ./install.sh runtime"
}

uninstall_widget() {
  need_kpackagetool
  if kpackagetool6 -t Plasma/Applet -s "$1" >/dev/null 2>&1; then
    kpackagetool6 -t Plasma/Applet -r "$1" >/dev/null
    say "Removed widget $1 (the shared service keeps running for the other widget)"
  else
    say "Widget $1 is not installed"
  fi
}

uninstall_runtime() {
  purge=${1:-}
  if [ -x "$BINDIR/klaude-monitor" ]; then
    "$BINDIR/klaude-monitor" hooks uninstall || true
  fi
  if command -v systemctl >/dev/null 2>&1; then
    systemctl --user disable --now klaude-monitord.service >/dev/null 2>&1 || true
  fi
  rm -f "$UNITDIR/klaude-monitord.service" "$DATADIR/dbus-1/services/$BUS.service" \
    "$BINDIR/klaude-monitord" "$BINDIR/klaude-monitor" "$BINDIR/klaude-monitor-hook" \
    "$DATADIR/icons/hicolor/scalable/apps/klaude-monitor.svg" "$DATADIR/applications/klaude-monitor.desktop"
  rm -rf "$LIBDIR"
  command -v systemctl >/dev/null 2>&1 && systemctl --user daemon-reload 2>/dev/null || true
  if [ "$purge" = "--purge" ]; then
    rm -rf "$STATEDIR/klaude-monitor" "$CONFIGDIR/klaude-monitor"
    say "Removed the service, its history and its settings"
  else
    say "Removed the service (history kept in $STATEDIR/klaude-monitor; use --purge to delete it)"
  fi
  for id in $PANEL_ID $DESKTOP_ID; do
    if command -v kpackagetool6 >/dev/null 2>&1 && kpackagetool6 -t Plasma/Applet -s "$id" >/dev/null 2>&1; then
      warn "widget $id is still installed and will show 'service not installed'"
    fi
  done
}

status() {
  printf 'service files : %s\n' "$([ -x "$BINDIR/klaude-monitord" ] && echo installed || echo missing)"
  if command -v systemctl >/dev/null 2>&1; then
    printf 'service state : %s\n' "$(systemctl --user is-active klaude-monitord.service 2>/dev/null || true)"
  fi
  for id in $PANEL_ID $DESKTOP_ID; do
    if command -v kpackagetool6 >/dev/null 2>&1 && kpackagetool6 -t Plasma/Applet -s "$id" >/dev/null 2>&1; then
      printf '%-14s: installed\n' "${id##*.}"
    else
      printf '%-14s: not installed\n' "${id##*.}"
    fi
  done
  [ -x "$BINDIR/klaude-monitor" ] && "$BINDIR/klaude-monitor" hooks status || true
}

cmd=${1:-help}
shift || true
case $cmd in
  runtime)
    install_runtime
    if [ "${1:-}" = "--hooks" ]; then install_hooks; fi
    ;;
  panel) sh "$ROOT/tools/build.sh" >/dev/null && install_widget $PANEL_ID ;;
  desktop) sh "$ROOT/tools/build.sh" >/dev/null && install_widget $DESKTOP_ID ;;
  all)
    install_runtime
    if [ "${1:-}" = "--hooks" ]; then install_hooks; fi
    sh "$ROOT/tools/build.sh" >/dev/null
    install_widget $PANEL_ID
    install_widget $DESKTOP_ID
    ;;
  hooks) install_hooks ;;
  uninstall-panel) uninstall_widget $PANEL_ID ;;
  uninstall-desktop) uninstall_widget $DESKTOP_ID ;;
  uninstall-runtime) uninstall_runtime "${1:-}" ;;
  status) status ;;
  *) sed -n '3,19p' "$0" | sed 's/^# \{0,1\}//' ;;
esac
