#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
# Assemble the two plasmoid packages into build/: copy the shared QML into each package, add the
# icon, compile the translations, and zip them as .plasmoid files (for GitHub releases / KDE Store).
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT="$ROOT/build"
rm -rf "$OUT"
mkdir -p "$OUT"

for name in panel desktop; do
  src="$ROOT/plasmoids/$name"
  id=$(sed -n 's/.*"Id": *"\([^"]*\)".*/\1/p' "$src/metadata.json")
  dst="$OUT/$id"
  cp -r "$src" "$dst"
  mkdir -p "$dst/contents/ui/shared" "$dst/contents/images"
  cp "$ROOT"/shared/qml/* "$dst/contents/ui/shared/"
  cp "$ROOT/data/klaude-monitor.svg" "$dst/contents/images/"
  # The service travels inside each widget, so a widget installed from the KDE Store can install it
  # (see shared/qml/ServiceSetup.qml). Same layout as the repository: install.sh runtime works as is.
  mkdir -p "$dst/contents/runtime/daemon"
  cp -r "$ROOT/hook" "$ROOT/data" "$ROOT/install.sh" "$dst/contents/runtime/"
  cp -r "$ROOT/daemon/klaude_monitord" "$dst/contents/runtime/daemon/"
  find "$dst/contents/runtime" -name '__pycache__' -type d -prune -exec rm -rf {} +
  version=$(sed -n 's/^__version__ = "\(.*\)"/\1/p' "$ROOT/daemon/klaude_monitord/__init__.py")
  printf '// Generated by tools/build.sh\n.pragma library\nvar version = "%s";\n' "$version" >"$dst/contents/ui/shared/RuntimeInfo.js"
  if command -v msgfmt >/dev/null 2>&1; then
    for po in "$ROOT"/po/*.po; do
      [ -e "$po" ] || continue
      lang=$(basename "$po" .po)
      mkdir -p "$dst/contents/locale/$lang/LC_MESSAGES"
      msgfmt -o "$dst/contents/locale/$lang/LC_MESSAGES/plasma_applet_$id.mo" "$po"
    done
  else
    echo "msgfmt not found: building without translations" >&2
  fi
  (cd "$dst" && zip -qr "$OUT/$id.plasmoid" .)
  echo "built $dst ($id.plasmoid)"
done
